version: '3.9'

services:
  telegram-news-bot:
    build: .
    container_name: telegram-news-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bot-network:
    external: true
    name: data-sink_default